// src/lib/workoutPresets.js
// Exercise presets per day type. "Jeff Nippard" = current app default.

const failurePolicy = { repeatFailures: 2, deloadPercent: 0.1 };

const JEFF_NIPPARD_PUSH = [
  {
    exerciseId: 'dumbbellBenchPress',
    name: 'Dumbbell Bench Press',
    increment: 5,
    rounding: 2.5,
    startWeight: 50,
    repScheme: { type: 'fixed', targetReps: 5, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'larsenPress',
    name: 'Larsen Press',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 45,
    repScheme: { type: 'fixed', targetReps: 10, sets: 2 },
    failurePolicy,
  },
  {
    exerciseId: 'standingArnoldPress',
    name: 'Standing Arnold Press',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 25,
    repScheme: { type: 'range', minReps: 8, maxReps: 10, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'deficitPushups',
    name: 'Deficit Push-ups',
    increment: 5,
    rounding: 2.5,
    startWeight: 0,
    repScheme: { type: 'range', minReps: 12, maxReps: 15, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'lateralRaises',
    name: 'Lateral Raises',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 10,
    repScheme: { type: 'range', minReps: 12, maxReps: 15, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'skullCrushers',
    name: 'Skull-crushers',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 20,
    repScheme: { type: 'fixed', targetReps: 15, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'tricepKickback',
    name: 'Single-arm Tricep Kickback',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 15,
    repScheme: { type: 'fixed', targetReps: 12, sets: 2 },
    failurePolicy,
  },
];

const JEFF_NIPPARD_PULL = [
  {
    exerciseId: 'pullUps',
    name: 'Pull-ups',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 0,
    repScheme: { type: 'fixed', targetReps: 10, sets: 4 },
    failurePolicy,
  },
  {
    exerciseId: 'rearDeltRaises',
    name: 'Rear Delt Raises',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 10,
    repScheme: { type: 'range', minReps: 12, maxReps: 15, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'latPulldowns',
    name: 'Lat Pulldowns',
    increment: 5,
    rounding: 2.5,
    startWeight: 80,
    repScheme: { type: 'range', minReps: 10, maxReps: 12, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'hammerCurls',
    name: 'Hammer Curls',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 20,
    repScheme: { type: 'range', minReps: 10, maxReps: 12, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'preacherCurls',
    name: 'Preacher Curls',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 25,
    repScheme: { type: 'range', minReps: 10, maxReps: 12, sets: 3 },
    failurePolicy,
  },
];

const JEFF_NIPPARD_LEGS = [
  {
    exerciseId: 'bulgarianSplitSquats',
    name: 'Bulgarian Split Squats',
    increment: 5,
    rounding: 2.5,
    startWeight: 30,
    repScheme: { type: 'fixed', targetReps: 4, sets: 4 },
    failurePolicy,
  },
  {
    exerciseId: 'bulgarianSplitSquatsPause',
    name: 'Bulgarian Split Squats (Pause)',
    increment: 5,
    rounding: 2.5,
    startWeight: 20,
    repScheme: { type: 'fixed', targetReps: 5, sets: 2 },
    failurePolicy,
  },
  {
    exerciseId: 'romanianDeadlifts',
    name: 'Romanian Deadlifts',
    increment: 5,
    rounding: 2.5,
    startWeight: 95,
    repScheme: { type: 'fixed', targetReps: 10, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'dumbbellGobletSquat',
    name: 'Dumbbell Goblet Squat',
    increment: 5,
    rounding: 2.5,
    startWeight: 60,
    repScheme: { type: 'range', minReps: 10, maxReps: 12, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'calfRaises',
    name: 'Calf Raises',
    increment: 5,
    rounding: 2.5,
    startWeight: 50,
    repScheme: { type: 'range', minReps: 15, maxReps: 20, sets: 3 },
    failurePolicy,
  },
  {
    exerciseId: 'weightedCrunches',
    name: 'Weighted Crunches',
    increment: 5,
    rounding: 2.5,
    startWeight: 20,
    repScheme: { type: 'range', minReps: 12, maxReps: 20, sets: 3 },
    failurePolicy,
    modality: 'dumbbell',
  },
];

const JEFF_NIPPARD_UPPER = [
  {
    exerciseId: 'pullUp',
    name: 'Pull Up',
    increment: 0,
    rounding: 0,
    startWeight: 0,
    repScheme: { type: 'fixed', targetReps: 10, sets: 2 },
    failurePolicy,
    modality: 'bodyweight',
    rest: '3 min',
  },
  {
    exerciseId: 'closeGripInclineDumbbellPress',
    name: 'Close Grip Incline Dumbbell Press',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 40,
    repScheme: { type: 'custom', sets: 3, reps: [8, 5, 12] },
    failurePolicy,
    modality: 'dumbbell',
    rest: '2 min',
  },
  {
    exerciseId: 'dumbbellRow',
    name: 'Dumbbell Row',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 45,
    repScheme: { type: 'fixed', targetReps: 12, sets: 3 },
    failurePolicy,
    modality: 'dumbbell',
    rest: '2 min',
  },
  {
    exerciseId: 'dumbbellLateralRaise',
    name: 'Dumbbell Lateral Raise',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 25,
    repScheme: { type: 'fixed', targetReps: 12, sets: 3 },
    failurePolicy,
    modality: 'dumbbell',
    rest: '1 min',
  },
  {
    exerciseId: 'dumbbellBicepCurl',
    name: 'Dumbbell Bicep Curl',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 25,
    repScheme: { type: 'fixed', targetReps: 12, sets: 3 },
    failurePolicy,
    modality: 'dumbbell',
    rest: '1 min',
  },
  {
    exerciseId: 'diamondPushUp',
    name: 'Diamond Push Up',
    increment: 0,
    rounding: 0,
    startWeight: 0,
    repScheme: { type: 'fixed', targetReps: 25, sets: 1 },
    failurePolicy,
    modality: 'bodyweight',
    rest: '1 min',
  },
];

const JEFF_NIPPARD_LOWER = [
  {
    exerciseId: 'trapBarDeadlift',
    name: 'Dumbbell Deadlift',
    increment: 5,
    rounding: 2.5,
    startWeight: 120,
    hasWarmups: true,
    warmupPercentages: [0.5, 0.65, 0.85],
    repScheme: { type: 'fixed', targetReps: 5, sets: 1 },
    failurePolicy,
    modality: 'dumbbell',
    rest: '3 min',
  },
  {
    exerciseId: 'dumbbellRomanianDeadlift',
    name: 'Dumbbell Romanian Deadlift',
    increment: 5,
    rounding: 2.5,
    startWeight: 50,
    repScheme: { type: 'fixed', targetReps: 8, sets: 2 },
    failurePolicy,
    modality: 'dumbbell',
    rest: '3 min',
  },
  {
    exerciseId: 'dumbbellGobletSquat',
    name: 'Dumbbell Goblet Squat',
    increment: 5,
    rounding: 2.5,
    startWeight: 60,
    hasWarmups: true,
    warmupPercentages: [0.5, 0.75],
    repScheme: { type: 'fixed', targetReps: 12, sets: 4 },
    failurePolicy,
    modality: 'dumbbell',
    rest: '2 min',
  },
  {
    exerciseId: 'dumbbellStepUp',
    name: 'Dumbbell Step Up',
    increment: 5,
    rounding: 2.5,
    startWeight: 35,
    repScheme: { type: 'fixed', targetReps: 10, sets: 3 },
    failurePolicy,
    modality: 'dumbbell',
    rest: '2 min',
  },
  {
    exerciseId: 'seatedDumbbellCalfRaise',
    name: 'Seated Dumbbell Calf Raise',
    increment: 5,
    rounding: 2.5,
    startWeight: 10,
    repScheme: { type: 'fixed', targetReps: 20, sets: 4 },
    failurePolicy,
    modality: 'dumbbell',
    rest: '1 min',
  },
  {
    exerciseId: 'hangingLegRaise',
    name: 'Hanging Leg Raise',
    increment: 0,
    rounding: 0,
    startWeight: 0,
    repScheme: { type: 'fixed', targetReps: 8, sets: 5 },
    failurePolicy,
    modality: 'bodyweight',
    rest: '1 min',
  },
];

const JEFF_NIPPARD_FULL = [
  {
    exerciseId: 'trapBarDeadlift',
    name: 'Dumbbell Deadlift',
    increment: 5,
    rounding: 2.5,
    startWeight: 135,
    repScheme: { type: 'fixed', targetReps: 5, sets: 1 },
    failurePolicy,
    modality: 'dumbbell',
    hasWarmups: true,
    warmupPercentages: [0.5, 0.65, 0.85],
    rest: '3 min',
  },
  {
    exerciseId: 'dumbbellRDL',
    name: 'Dumbbell RDL',
    increment: 5,
    rounding: 2.5,
    startWeight: 45,
    repScheme: { type: 'fixed', targetReps: 8, sets: 2 },
    failurePolicy,
    modality: 'dumbbell',
    rest: '3 min',
  },
  {
    exerciseId: 'closeGripInclineDumbbellPress',
    name: 'Close Grip Incline Dumbbell Press',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 40,
    repScheme: { type: 'custom', sets: 3, reps: [8, 5, 12] },
    failurePolicy,
    modality: 'dumbbell',
    rest: '2 min',
  },
  {
    exerciseId: 'chinUps',
    name: 'Chin-ups',
    increment: 0,
    rounding: 0,
    startWeight: 0,
    repScheme: { type: 'fixed', targetReps: 10, sets: 2 },
    failurePolicy,
    modality: 'bodyweight',
    rest: '2 min',
  },
  {
    exerciseId: 'gobletSquats',
    name: 'Goblet Squats',
    increment: 5,
    rounding: 2.5,
    startWeight: 60,
    repScheme: { type: 'fixed', targetReps: 12, sets: 5 },
    failurePolicy,
    modality: 'dumbbell',
    hasWarmups: true,
    warmupPercentages: [0.5, 0.7],
    rest: '2 min',
  },
  {
    exerciseId: 'singleArmDumbbellRow',
    name: 'Single Arm DB Row',
    increment: 2.5,
    rounding: 2.5,
    startWeight: 30,
    repScheme: { type: 'fixed', targetReps: 12, sets: 4 },
    failurePolicy,
    modality: 'dumbbell',
    hasWarmups: true,
    warmupPercentages: [0.5, 0.7],
    rest: '2 min',
  },
  {
    exerciseId: 'diamondPushups',
    name: 'Diamond Push-ups',
    increment: 0,
    rounding: 0,
    startWeight: 0,
    repScheme: { type: 'amrap', sets: 1 },
    failurePolicy,
    modality: 'bodyweight',
    rest: '1 min',
  },
];

export const PRESETS = {
  jeffNippard: {
    push: JEFF_NIPPARD_PUSH,
    pull: JEFF_NIPPARD_PULL,
    legs: JEFF_NIPPARD_LEGS,
    upper: JEFF_NIPPARD_UPPER,
    lower: JEFF_NIPPARD_LOWER,
    full: JEFF_NIPPARD_FULL,
  },
};

export const PRESET_OPTIONS = [{ value: 'jeffNippard', label: 'Jeff Nippard' }];

export function getPresetDefs(presetName, dayType) {
  const preset = PRESETS[presetName] ?? PRESETS.jeffNippard;
  return preset[dayType] ?? [];
}
